<html><head><title>The WebScript Language</title></head>
<body bgcolor="#ffffff">

<!--start of banner -->
<!--#include virtual="/includes/framesetheader" -->
<!-- end of banner -->

<!--start of path -->
<font face="Geneva,Helvetica,Arial" size="1">
<b>PATH<spacer type="horizontal" size="5">&nbsp;</b>
 <a href="../../../../../webobjects.html" target="_top">WebObjects 4.0 Documentation</a> <b>&gt;</b>
 <a href="DevGuideTOC.html" target="_top">WebObjects Developer's Guide</a>
</font>
<br><br>
<!--end of path -->

 
<a href="WebScript.html"><IMG SRC="ArrowUp.gif">Table of Contents</a> <a href="WebScript19.html"><IMG SRC="ArrowLeft.gif">Previous Section</a>
 
<a name="10273">
<h3> Handling an Exception </h3>
</a><a name="10279">
Where and how an exception is handled depends on the context where the exception was raised. In general, a raise message is sent to an NSException object within the domain of an exception handler. An exception handler is contained within a control structure created by the keywords NS_DURING, NS_HANDLER, and NS_ENDHANDLER, as shown here:<p>
</a><pre><a name="10032">.<br>
.<br>
NS_DURING<br>
	[<em>some code</em>];<br>
	[<em>some more code</em>];<br>
NS_HANDLER<br>
	[<em>exception handler code</em>];<br>
	[<em>more exception handler code</em>];<br>
NS_ENDHANDLER<br>
.<br>
.
</a></pre><a name="10572">
The section of code between NS_DURING and NS_HANDLER is the <em>exception handling domain</em>; the section between NS_HANDLER and NS_ENDHANDLER is the <em>local exception handler</em>. The normal flow of program execution is marked by the gray arrow; the code within the local exception handler is executed only if an exception is raised. Sending a <strong>raise</strong> message to an exception object causes program control to jump to the first executable line following NS_HANDLER.<p>
</a><a name="9861">
Although an exception can be raised directly within the exception handling domain, exceptions more often arise indirectly from a method invoked from the domain. No matter how deep in a call sequence the exception is raised, execution jumps to the local exception handler (assuming there are no intervening exception handlers, as discussed in the next section). In this way, exceptions raised at a low level can be caught at a high level.<p>
</a><a name="9883">
You may leave the exception handling domain (the section of code between NS_DURING and NS_HANDLER) by:<p>
</a><ul><a name="9885">
<p><li>Raising an exception.
</a><a name="9887">
<p><li>Calling NS_VALUERETURN(), which returns a value from the DURING block.
</a><a name="9889">
<p><li>Calling NS_VOIDRETURN, which returns void from the DURING block.
</a><a name="10140">
<p><li>"Falling off the end."
</a></ul><a name="9894">
"Falling off the end" is simply the normal path of execution-after all statements in the exception handling domain are executed, execution continues on the line following NS_ENDHANDLER.<p>
</a><a name="10534">
<B>Note: </B> You can't use return to exit an exception handling domain-errors will result.<p>
</a>
<P>
 
<a href="WebScript.html"><IMG SRC="ArrowUp.gif">Table of Contents</a> <a href="WebScript21.html"><IMG SRC="ArrowRight.gif">Next Section</a>
<P>


</body>
</html>
