<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<title>Exception Programming Topics for Cocoa: Handling Exceptions</title>
	<meta id="Generator" name="Generator" content="Gutenberg"/>
	<meta id="GeneratorVersion" name="GeneratorVersion" content="v132"/>
	<meta http-equiv="content-type" content="text/html;charset=utf-8"/>
	<meta id="Copyright" name="Copyright" content="Copyright 2009 Apple Inc. All Rights Reserved."/>
	<meta id="IndexTitle" name="IndexTitle" content="Handling Exceptions"/>
	<meta id="xcode-display" name="xcode-display" content="render"/>
	<meta id="toc-file" name="toc-file" content="../toc.html"/>
	<meta id="RESOURCES" content="../../../../Resources" />
	
	<link rel="stylesheet" type="text/css" href="../../../../Resources/CSS/frameset_styles.css"/>
	<script language="JavaScript" type="text/javascript" src="../../../../Resources/JavaScript/lib/prototype.js"></script>
	<script language="JavaScript" type="text/javascript" src="../../../../Resources/JavaScript/lib/scriptaculous.js"></script>
	<script language="JavaScript" type="text/javascript" src="../../../../Resources/JavaScript/page.js"></script>
	<script language="JavaScript" type="text/javascript" src="../../../../Resources/JavaScript/pedia.js"></script>
	<!--[if lte IE 6]>
		<style type="text/css">
			/*<![CDATA[*/ 
			html {overflow-x:auto; overflow-y:hidden;  }
			/*]]>*/
		</style>
	<![endif]-->
</head>
<body bgcolor="#ffffff" onload="initialize_page();"><a name="//apple_ref/doc/uid/20000059" title="Handling Exceptions"></a>
    <noscript>
    <div id="tocMenu">
        <iframe id="toc_content" name="toc_content" SRC="../toc.html" width="210" height="100%" align="left" frameborder="0">This document set is best viewed in a browser that supports iFrames.</iframe>
    </div>
    </noscript>
    <div id="bodyText">
        <a name="top"></a>
        <div class="hideOnPrint hideInXcode">
        <!-- start of header -->
        <!--#include virtual="/includes/framesetheader" -->
        <!-- end of header -->
        </div>
        
        <!-- start of path -->
<div class="breadcrumb hideOnPrint hideInXcode"><a href="http://developer.apple.com/" target="_top">ADC Home</a> &gt; <a href="../../../../../referencelibrary/index.html#//apple_ref/doc/uid/TP30000943" target="_top">Reference Library</a> &gt; <a href="../../../../index.html#//apple_ref/doc/uid/TP30000440" target="_top">Guides</a> &gt; <a href="../../../index.html#//apple_ref/doc/uid/TP30000440-TP30000416" target="_top">Cocoa</a> &gt; <a href="../../../ObjectiveCLanguage-date.html#//apple_ref/doc/uid/TP30000440-TP30000416-TP30000856" target="_top">Objective-C Language</a> &gt; <a href="../index.html" target="_top">Exception Programming Topics for Cocoa</a> &gt; </div><br class="hideInXcode"/><!-- end of path -->
        
        <div class="mini_nav_text" align="left">
        <span class="navButtons">
        <a href="../Concepts/PredefinedExceptions.html">&lt; Previous Page</a><span style="margin-left: 8px"><a href="RaisingExceptions.html">Next Page &gt;</a></span>
        </span>
        <span id="showHideTOCUpperSpan">
        <a href="#" onclick="showHideTOC();"><img src="../../../../Resources/Images/show_toc_icon.gif" width="15" height="14" border="0" style="margin-bottom: -2px;" alt="" hideText="Hide TOC" showText="Show TOC" /></a> <a href="#" onclick="showHideTOC();">Hide TOC</a>
        </span>
        </div>
        
        
        <a name="//apple_ref/doc/uid/20000059-SW1" title="Handling Exceptions"></a><hr /><H1><a name="//apple_ref/doc/uid/20000059-BBCHGJIJ" title="Handling Exceptions"></a>Handling Exceptions</H1><p>The exception handling mechanisms available to Objective-C programs are effective ways of dealing with exceptional conditions. They decouple the detection and handling of these conditions and automate the propagation of the exception from the point of detection to the point of handling. As a result, your code can be much cleaner, easier to write correctly, and easier to maintain.</p><p>The following sections describe how to handle exceptions using compiler directives or, for appropriate projects, the legacy mechanism of exception-handling macros.</p><div class="importantbox"><a name="//apple_ref/doc/uid/20000059-DontLinkElementID_15" title="Important:"></a><p><strong>Important:</strong>&nbsp;The compiler directives discussed below were introduced in Mac OS X v10.3. An application that uses these directives for exception handling cannot run on earlier versions of the operating system.</p><p></p></div>
<!-- This template is being used for both PDF and HTML. -->

    
    <!-- TopicBook.pm uses this template for its miniTOCs, but needs a different title. -->
    <h4>Contents:</h4>
    
    
    <p class="blockquote">
    
        
			
			
				<a href="HandlingExceptions.html#//apple_ref/doc/uid/20000059-DontLinkElementID_4">Handling Exceptions Using Compiler Directives</a>
				
			<br/>
			
        
			
			
				<a href="HandlingExceptions.html#//apple_ref/doc/uid/20000059-SW7">Exception Handling and Memory Management</a>
				
			<br/>
			
        
			
			
				<a href="HandlingExceptions.html#//apple_ref/doc/uid/20000059-DontLinkElementID_5">Handling Exceptions Using Macros</a>
				
			<br/>
			
        

    </p><br/>

<a name="//apple_ref/doc/uid/20000059-DontLinkElementID_4" title="Handling Exceptions Using Compiler Directives"></a><h2>Handling Exceptions Using Compiler Directives</h2><p>Starting with version 3.3 of the GNU Compiler Collection (GCC), the compiler provides runtime support for exception handling. To turn on this support, make sure the <code>-fobj-exceptions</code> flag is turned on; this is enabled through the Enable Objective-C Exceptions build option in Xcode. </p><p>The compiler support for exceptions is based on four compiler directives:</p><ul class="ul"><li class="li"><p><code>@try</code> —Defines a block of code that is an exception handling domain: code that can potentially throw an exception. </p></li><li class="li"><p><code>@catch()</code> —Defines a block containing code for handling the exception thrown in the <code>@try</code> block. The parameter of <code>@catch</code> is the exception object thrown locally; this is usually an <code>NSException</code> object, but can be other types of objects, such as <code><a href="../../../Reference/Foundation/Classes/NSString_Class/Reference/NSString.html#//apple_ref/occ/cl/NSString" target="_top">NSString</a></code> objects..</p></li><li class="li"><p><code>@finally</code> — Defines a block of related code that is subsequently executed whether an exception is thrown or not.</p></li><li class="li"><p><code>@throw</code> — Throws an exception; this directive is almost identical in behavior to the <code><a href="../../../Reference/Foundation/Classes/NSException_Class/Reference/Reference.html#//apple_ref/occ/instm/NSException/raise" target="_top">raise</a></code> method of <code>NSException</code>. You usually throw <code>NSException</code> objects, but are not limited to them. For more information about <code>@throw</code>, see <span class="content_text"><a href="RaisingExceptions.html#//apple_ref/doc/uid/20000058-BBCCFIBF">“Throwing Exceptions.”</a></span></p></li></ul><div class="importantbox"><a name="//apple_ref/doc/uid/20000059-DontLinkElementID_16" title="Important:"></a><p><strong>Important:</strong>&nbsp;Although you can throw and catch objects other than <code>NSException</code> objects, the Cocoa frameworks themselves might only catch <code>NSException</code> objects for some conditions. So if you throw other types of objects, the Cocoa handlers for that exception might not run, with undefined results. (Conversely, non-<code>NSException</code> objects that you throw could be caught by some Cocoa handlers.) For these reasons, it is recommended that you throw <code>NSException</code> objects only, while being prepared to catch exception objects of all types..</p><p></p></div><p>The <code>@try</code>, <code>@catch</code>, and <code>@finally</code> directives constitute a control structure. The section of code between the braces in <code>@try</code> is the exception handling domain; the code in a <code>@catch</code> block is a local exception handler; the <code>@finally</code> block of code is a common “housekeeping” section. In <span class="content_text">Figure 1</span>, the normal flow of program execution is marked by the gray arrow; the code within the local exception handler is executed only if an exception is thrown—either by the local exception handling domain or one further down the call sequence. The throwing (or raising) of an exception causes program control to jump to the first executable line of the local exception handler. After the exception is handled, control “falls through” to the <code>@finally</code> block; if no exception is thrown, control jumps from the <code>@try</code> block to the <code>@finally</code> block. </p><br/><div><a name="//apple_ref/doc/uid/20000059-SW6" title="Figure 1Flow of exception handling using compiler directives"></a><p><strong>Figure 1&nbsp;&nbsp;</strong>Flow of exception handling using compiler directives</p><img src = "Art/flow_control_directive.gif" alt = "Flow of exception handling using compiler directives" width="474" height="287"></div><br/><p>Where and how an exception is handled depends on the context where the exception was raised (although most exceptions in most programs go uncaught until they reach the top-level <code><a href="../../../Reference/ApplicationKit/Classes/NSApplication_Class/Reference/Reference.html#//apple_ref/occ/cl/NSApplication" target="_top">NSApplication</a></code> handler). In general, an exception object is thrown (or raised) within the domain of an exception handler. Although you can throw an exception directly within a local exception handling domain, an exception is more likely thrown (through <code>@throw</code> or <code><a href="../../../Reference/Foundation/Classes/NSException_Class/Reference/Reference.html#//apple_ref/occ/instm/NSException/raise" target="_top">raise</a></code>) indirectly from a method invoked from the domain. No matter how deep in a call sequence the exception is thrown, execution jumps to the local exception handler (assuming there are no intervening exception handlers, as discussed in <span class="content_text"><a href="NestingExceptionHandlers.html#//apple_ref/doc/uid/20000060-CJBBFDIF">“Nesting Exception Handlers”</a></span>). In this way, exceptions raised at a low level can be caught at a high level. </p><p><span class="content_text">Listing 1</span> illustrates how you might use the <code>@try</code>, <code>@catch</code>, and <code>@finally</code> compiler directives. In this example, the <code>@catch</code> block handles any exception thrown lower in the calling sequence as a consequence of the <code><a href="../../../Reference/Foundation/Protocols/NSKeyValueCoding_Protocol/Reference/Reference.html#//apple_ref/occ/instm/NSObject/setValue:forKeyPath:" target="_top">setValue:forKeyPath:</a></code> message by setting the affected property to <code>nil</code> instead. The message in the <code>@finally</code> block is sent whether an exception is thrown or not.</p><a name="//apple_ref/doc/uid/20000059-SW2" title="Listing 1Handling an exception using compiler directives"></a><p class="codesample"><strong>Listing 1&nbsp;&nbsp;</strong>Handling an exception using compiler directives</p><div class="codesample"><table><tr><td scope="row"><pre>- (void)endSheet:(NSWindow *)sheet<span></span></pre></td></tr><tr><td scope="row"><pre>{<span></span></pre></td></tr><tr><td scope="row"><pre>    BOOL success = [predicateEditorView commitEditing];<span></span></pre></td></tr><tr><td scope="row"><pre>    if (success == YES) {<span></span></pre></td></tr><tr><td scope="row"><pre> <span></span></pre></td></tr><tr><td scope="row"><pre>        @try {<span></span></pre></td></tr><tr><td scope="row"><pre>            [treeController setValue:[predicateEditorView predicate] forKeyPath:@"selection.predicate"];<span></span></pre></td></tr><tr><td scope="row"><pre>        }<span></span></pre></td></tr><tr><td scope="row"><pre> <span></span></pre></td></tr><tr><td scope="row"><pre>        @catch ( NSException *e ) {<span></span></pre></td></tr><tr><td scope="row"><pre>            [treeController setValue:nil forKeyPath:@"selection.predicate"];<span></span></pre></td></tr><tr><td scope="row"><pre>        }<span></span></pre></td></tr><tr><td scope="row"><pre> <span></span></pre></td></tr><tr><td scope="row"><pre>        @finally {<span></span></pre></td></tr><tr><td scope="row"><pre>            [NSApp endSheet:sheet];<span></span></pre></td></tr><tr><td scope="row"><pre>        }<span></span></pre></td></tr><tr><td scope="row"><pre>    }<span></span></pre></td></tr><tr><td scope="row"><pre>}<span></span></pre></td></tr></table></div><p>One way to handle exceptions is to “promote” them to error messages that either inform users or request their intervention.  You can convert an exception into an <code><a href="../../../Reference/Foundation/Classes/NSError_Class/Reference/Reference.html#//apple_ref/occ/cl/NSError" target="_top">NSError</a></code> object and hand this object over to the Application Kit’s error-handling mechanism for display in an alert panel. You can also return them indirectly in methods that include an error parameter. <span class="content_text">Listing 2</span> shows an example of the latter in an Automator action’s implementation of <code><a href="../../../../AppleApplications/Reference/AutomatorFramework/Classes/AMAction_Class/Reference/Reference.html#//apple_ref/occ/instm/AMAction/runWithInput:fromAction:error:" target="_top">runWithInput:fromAction:error:</a></code> (in this case the error parameter is a pointer to an <code><a href="../../../Reference/Foundation/Classes/NSDictionary_Class/Reference/Reference.html#//apple_ref/occ/cl/NSDictionary" target="_top">NSDictionary</a></code> object rather than an <code>NSError</code> object). </p><a name="//apple_ref/doc/uid/20000059-SW3" title="Listing 2Converting an exception into an error"></a><p class="codesample"><strong>Listing 2&nbsp;&nbsp;</strong>Converting an exception into an error</p><div class="codesample"><table><tr><td scope="row"><pre>- (id)runWithInput:(id)input fromAction:(AMAction *)anAction error:(NSDictionary **)errorInfo {<span></span></pre></td></tr><tr><td scope="row"><pre> <span></span></pre></td></tr><tr><td scope="row"><pre>    NSMutableArray *output = [NSMutableArray array];<span></span></pre></td></tr><tr><td scope="row"><pre>    NSString *actionMessage = nil;<span></span></pre></td></tr><tr><td scope="row"><pre>    NSArray *recipes = nil;<span></span></pre></td></tr><tr><td scope="row"><pre>    NSArray *summaries = nil;<span></span></pre></td></tr><tr><td scope="row"><pre> <span></span></pre></td></tr><tr><td scope="row"><pre>    // other code here....<span></span></pre></td></tr><tr><td scope="row"><pre> <span></span></pre></td></tr><tr><td scope="row"><pre>    @try {<span></span></pre></td></tr><tr><td scope="row"><pre>        if (managedObjectContext == nil) {<span></span></pre></td></tr><tr><td scope="row"><pre>            actionMessage = @"accessing user recipe library";<span></span></pre></td></tr><tr><td scope="row"><pre>            [self initCoreDataStack];<span></span></pre></td></tr><tr><td scope="row"><pre>        }<span></span></pre></td></tr><tr><td scope="row"><pre>        actionMessage = @"finding recipes";<span></span></pre></td></tr><tr><td scope="row"><pre>        recipes = [self recipesMatchingSearchParameters];<span></span></pre></td></tr><tr><td scope="row"><pre>        actionMessage = @"generating recipe summaries";<span></span></pre></td></tr><tr><td scope="row"><pre>        summaries = [self summariesFromRecipes:recipes];<span></span></pre></td></tr><tr><td scope="row"><pre>    }<span></span></pre></td></tr><tr><td scope="row"><pre>    @catch (NSException *exception) {<span></span></pre></td></tr><tr><td scope="row"><pre>        NSMutableDictionary *errorDict = [NSMutableDictionary dictionary];<span></span></pre></td></tr><tr><td scope="row"><pre>        [errorDict setObject:[NSString stringWithFormat:@"Error %@: %@", actionMessage, [exception reason]] forKey:OSAScriptErrorMessage];<span></span></pre></td></tr><tr><td scope="row"><pre>        [errorDict setObject:[NSNumber numberWithInt:errOSAGeneralError] forKey:OSAScriptErrorNumber];<span></span></pre></td></tr><tr><td scope="row"><pre>        *errorInfo = errorDict;<span></span></pre></td></tr><tr><td scope="row"><pre>        return input;<span></span></pre></td></tr><tr><td scope="row"><pre>    }<span></span></pre></td></tr><tr><td scope="row"><pre> <span></span></pre></td></tr><tr><td scope="row"><pre>    // other code here ....<span></span></pre></td></tr><tr><td scope="row"><pre>}<span></span></pre></td></tr></table></div><div class="notebox"><a name="//apple_ref/doc/uid/20000059-DontLinkElementID_17" title="Note"></a><p><strong>Note:</strong>&nbsp;For more on the Application Kit’s error-handling mechanims, see <em><a href="../../ErrorHandlingCocoa/index.html#//apple_ref/doc/uid/TP40001806" target="_top">Error Handling Programming Guide For Cocoa</a></em>. To learn more about Automator actions, see <em><a href="../../../../AppleApplications/Conceptual/AutomatorConcepts/index.html#//apple_ref/doc/uid/TP40001450" target="_top">Automator Programming Guide</a></em>. </p></div><p>You can have a sequence of <code>@catch</code> error-handling blocks. Each block handles an exception object of a different type. You should order this sequence of <code>@catch</code> blocks from the most-specific to the least-specific type of exception object (the least specific type being <code>id</code>), as shown in <span class="content_text">Listing 3</span>.  This sequencing allows you to tailor the processing of exceptions as groups.</p><a name="//apple_ref/doc/uid/20000059-SW4" title="Listing 3Sequence of exception handlers"></a><p class="codesample"><strong>Listing 3&nbsp;&nbsp;</strong>Sequence of exception handlers</p><div class="codesample"><table><tr><td scope="row"><pre>@try {<span></span></pre></td></tr><tr><td scope="row"><pre>    // code that throws an exception<span></span></pre></td></tr><tr><td scope="row"><pre>    ...<span></span></pre></td></tr><tr><td scope="row"><pre>}<span></span></pre></td></tr><tr><td scope="row"><pre>@catch (CustomException *ce) { // most specific type<span></span></pre></td></tr><tr><td scope="row"><pre>    // handle exception ce<span></span></pre></td></tr><tr><td scope="row"><pre>    ...<span></span></pre></td></tr><tr><td scope="row"><pre>}<span></span></pre></td></tr><tr><td scope="row"><pre>@catch (NSException *ne) { // less specific type<span></span></pre></td></tr><tr><td scope="row"><pre>    // do whatever recovery is necessary at his level<span></span></pre></td></tr><tr><td scope="row"><pre>    ...<span></span></pre></td></tr><tr><td scope="row"><pre>    // rethrow the exception so it's handled at a higher level<span></span></pre></td></tr><tr><td scope="row"><pre>    @throw;<span></span></pre></td></tr><tr><td scope="row"><pre>}<span></span></pre></td></tr><tr><td scope="row"><pre>@catch (id ue) { // least specific type<span></span></pre></td></tr><tr><td scope="row"><pre>    // code that handles this exception<span></span></pre></td></tr><tr><td scope="row"><pre>    ...<span></span></pre></td></tr><tr><td scope="row"><pre>}<span></span></pre></td></tr><tr><td scope="row"><pre>@finally {<span></span></pre></td></tr><tr><td scope="row"><pre>    // perform tasks necessary whether exception occurred or not<span></span></pre></td></tr><tr><td scope="row"><pre>    ...<span></span></pre></td></tr><tr><td scope="row"><pre>}<span></span></pre></td></tr></table></div><div class="notebox"><a name="//apple_ref/doc/uid/20000059-DontLinkElementID_18" title="Note"></a><p><strong>Note:</strong>&nbsp;You cannot use the <code>setjmp</code> and <code>longjmp</code> functions if the jump entails crossing an <code>@try</code> block. Since the code that your program calls may have exception-handling domains within it, avoid using <code>setjmp</code> and <code>longjmp</code> in your application. However, you may use <code>goto</code> or <code>return</code> to exit an exception handling domain. </p></div><a name="//apple_ref/doc/uid/20000059-SW7" title="Exception Handling and Memory Management "></a><h2>Exception Handling and Memory Management </h2><p>Using the exception-handling directives of Objective-C can complicate memory management, but with a little common sense you can avoid the pitfalls. To see how, let’s begin with the simple case: a method that, for the sake of efficiency, creates an object, uses it, and then releases it explicitly:</p><div class="codesample"><table><tr><td scope="row"><pre>- (void)doSomething {<span></span></pre></td></tr><tr><td scope="row"><pre>    NSMutableArray *anArray = [[NSMutableArray alloc] initWithCapacity:0];<span></span></pre></td></tr><tr><td scope="row"><pre>    [self doSomethingElse:anArray];<span></span></pre></td></tr><tr><td scope="row"><pre>    [anArray release];<span></span></pre></td></tr><tr><td scope="row"><pre>}<span></span></pre></td></tr></table></div><p>The problem here is obvious: If the <code>doSomethingElse:</code> method throws an exception there is a memory leak. But the solution is equally obvious: Move the <code><a href="../../../Reference/Foundation/Protocols/NSObject_Protocol/Reference/NSObject.html#//apple_ref/occ/intfm/NSObject/release" target="_top">release</a></code> to a <code>@finally</code> block:</p><div class="codesample"><table><tr><td scope="row"><pre>- (void)doSomething {<span></span></pre></td></tr><tr><td scope="row"><pre>    NSMutableArray *anArray = nil;<span></span></pre></td></tr><tr><td scope="row"><pre>    array = [[NSMutableArray alloc] initWithCapacity:0];<span></span></pre></td></tr><tr><td scope="row"><pre>    @try {<span></span></pre></td></tr><tr><td scope="row"><pre>        [self doSomethingElse:anArray];<span></span></pre></td></tr><tr><td scope="row"><pre>    }<span></span></pre></td></tr><tr><td scope="row"><pre>    @finally {<span></span></pre></td></tr><tr><td scope="row"><pre>        [anArray release];<span></span></pre></td></tr><tr><td scope="row"><pre>    }<span></span></pre></td></tr><tr><td scope="row"><pre>}<span></span></pre></td></tr></table></div><p>This pattern of using <code>@try...@finally</code> to release objects involved in an exception applies to other resources as well. If you have <code>malloc</code>’d blocks of memory or open file descriptors, <code>@finally</code> is a good place to free those; it’s also the ideal place to unlock any locks you’ve acquired. </p><p>Another, more subtle memory-management problem is over-releasing an exception object when there are internal <code><a href="../../../Reference/Foundation/Protocols/NSObject_Protocol/Reference/NSObject.html#//apple_ref/occ/intfm/NSObject/autorelease" target="_top">autorelease</a></code> pools. Almost all <code>NSException</code> objects (and other types of exception objects) are created autoreleased, which assigns them to the nearest (in scope) autorelease pool. When that pool is released, the exception is destroyed. A pool can be either released directly or as a result of an autorelease pool further down the stack (and thus further out in scope) being popped (that is, released). Consider this method:  </p><div class="codesample"><table><tr><td scope="row"><pre>- (void)doSomething {<span></span></pre></td></tr><tr><td scope="row"><pre>    NSAutoreleasePool *pool = [[NSAutoreleasePool alloc] init];<span></span></pre></td></tr><tr><td scope="row"><pre>    NSMutableArray *anArray = [[[NSMutableArray alloc] initWithCapacity:0] autorelease];<span></span></pre></td></tr><tr><td scope="row"><pre>    [self doSomethingElse:anArray];<span></span></pre></td></tr><tr><td scope="row"><pre>    [pool release];<span></span></pre></td></tr><tr><td scope="row"><pre>}<span></span></pre></td></tr></table></div><p>This code appears to be sound; if the <code>doSomethingElse:</code> message results in a thrown exception, the local autorelease pool will be released when a lower (or outer) autorelease pool on the stack is popped. But there is a potential problem. As explained in <span class="content_text"><a href="RaisingExceptions.html#//apple_ref/doc/uid/20000058-BBCCFIBF">“Throwing Exceptions,”</a></span> a rethrown exception causes its associated <code>@finally</code> block to be executed as an early side effect. If an outer autorelease pool is released in a <code>@finally</code> block, the local pool could be released <em>before</em> the exception is delivered, resulting in a “zombie” exception. </p><p>There are several ways to resolve this problem. The simplest is to refrain from releasing local autorelease pools in <code>@finally</code> blocks. Instead let a pop of a deeper pool take care of releasing the pool holding the exception object. However, if no deeper pool is ever popped as the exception propagates up the stack, the pools on the stack will leak memory; all objects in those pools remain unreleased until the thread is destroyed.  </p><p>An alternative approach would be to catch any thrown exception, retain it, and rethrow it . Then, in the <code>@finally</code> block, release the autorelease pool and autorelease the exception object.  <span class="content_text">Listing 4</span> shows how this might look in code. </p><a name="//apple_ref/doc/uid/20000059-SW5" title="Listing 4Releasing an autorelease pool containing an exception object"></a><p class="codesample"><strong>Listing 4&nbsp;&nbsp;</strong>Releasing an autorelease pool containing an exception object</p><div class="codesample"><table><tr><td scope="row"><pre>- (void)doSomething {<span></span></pre></td></tr><tr><td scope="row"><pre>    id savedException = nil;<span></span></pre></td></tr><tr><td scope="row"><pre>    NSAutoreleasePool *pool = [[NSAutoreleasePool alloc] init];<span></span></pre></td></tr><tr><td scope="row"><pre>    NSMutableArray *anArray = [[[NSMutableArray alloc] initWithCapacity:0] autorelease];<span></span></pre></td></tr><tr><td scope="row"><pre>    @try {<span></span></pre></td></tr><tr><td scope="row"><pre>        [self doSomethingElse:anArray];<span></span></pre></td></tr><tr><td scope="row"><pre>    }<span></span></pre></td></tr><tr><td scope="row"><pre>    @catch (NSException *theException) {<span></span></pre></td></tr><tr><td scope="row"><pre>        savedException = [theException retain];<span></span></pre></td></tr><tr><td scope="row"><pre>        @throw;<span></span></pre></td></tr><tr><td scope="row"><pre>    }<span></span></pre></td></tr><tr><td scope="row"><pre>    @finally {<span></span></pre></td></tr><tr><td scope="row"><pre>        [pool release];<span></span></pre></td></tr><tr><td scope="row"><pre>        [savedException autorelease];<span></span></pre></td></tr><tr><td scope="row"><pre>    }<span></span></pre></td></tr><tr><td scope="row"><pre>}<span></span></pre></td></tr></table></div><p>Doing this retains the thrown exception across the release of the interior autorelease pool—the pool the exception was put into on its way out of <code>doSomethingElse:</code>—and ensures that it is autoreleased in the next autorelease pool outward to it in scope (or, in another perspective, the autorelease pool below it on the stack). For things to work correctly, the release of the interior autorelease pool must occur before the retained exception object is autoreleased. </p><a name="//apple_ref/doc/uid/20000059-DontLinkElementID_5" title="Handling Exceptions Using Macros"></a><h2>Handling Exceptions Using Macros</h2><p>An exception handler is contained within a control structure created by the macros <code>NS_DURING</code>, <code>NS_HANDLER</code>, and <code>NS_ENDHANDLER</code>, as shown in <span class="content_text">Figure 2</span>.</p><div class="importantbox"><a name="//apple_ref/doc/uid/20000059-DontLinkElementID_19" title="Important:"></a><p><strong>Important:</strong>&nbsp;The exception macros are a legacy mechanism that should only be used when binary compatibility with versions of of the operating system prior to Mac OS X v10.3 is a concern.</p><p></p></div><br/><div><a name="//apple_ref/doc/uid/20000059-1037993" title="Figure 2Flow of exception handling using macros"></a><p><strong>Figure 2&nbsp;&nbsp;</strong>Flow of exception handling using macros</p><img src = "Art/flow_control.gif" alt = "Flow of exception handling using macros" width="389" height="296"></div><br/><p>The section of code between <code>NS_DURING</code> and <code>NS_HANDLER</code> is the exception handling domain; the section between <code>NS_HANDLER</code> and <code>NS_ENDHANDLER</code> is the local exception handler. The normal flow of program execution is marked by the gray arrow; the code within the local exception handler is executed only if an exception is raised. Sending a <code>raise</code> message to an exception object causes program control to jump to the first executable line following <code>NS_HANDLER</code>.</p><p>Although you can raise an exception directly within the exception handling domain, <code>raise</code> is more often invoked indirectly from a method invoked from the domain. No matter how deep in a call sequence the exception is raised, execution jumps to the local exception handler (assuming there are no intervening exception handlers, as discussed in <span class="content_text"><a href="NestingExceptionHandlers.html#//apple_ref/doc/uid/20000060-CJBBFDIF">“Nesting Exception Handlers”</a></span>). In this way, exceptions raised at a low level can be caught at a high level.</p><p>For example, in the following program excerpt, the local exception handler displays an alert dialog after detecting an exception having the name MyAppException. The local exception handler has access to the raised exception object through a local variable <code>localException</code>.</p><div class="codesample"><table><tr><td scope="row"><pre>NS_DURING<span></span></pre></td></tr><tr><td scope="row"><pre>    ...<span></span></pre></td></tr><tr><td scope="row"><pre>    if (someError)<span></span></pre></td></tr><tr><td scope="row"><pre>        [anException raise];<span></span></pre></td></tr><tr><td scope="row"><pre>    ...<span></span></pre></td></tr><tr><td scope="row"><pre>NS_HANDLER<span></span></pre></td></tr><tr><td scope="row"><pre>    if ([[localException name] isEqualToString:MyAppException]) {<span></span></pre></td></tr><tr><td scope="row"><pre>       NSRunAlertPanel(@"Error Panel", @"%@", @"OK", nil, nil,<span></span></pre></td></tr><tr><td scope="row"><pre>            localException);<span></span></pre></td></tr><tr><td scope="row"><pre>    }<span></span></pre></td></tr><tr><td scope="row"><pre>    [localException raise]; /* Re-raise the exception. */<span></span></pre></td></tr><tr><td scope="row"><pre>NS_ENDHANDLER<span></span></pre></td></tr></table></div><p>You may leave the exception handling domain (the section of code between <code>NS_DURING</code> and <code>NS_HANDLER</code>) by:</p><ul class="ul"><li class="li"><p>Raising an exception.</p></li><li class="li"><p>Calling <code>NS_VALUERETURN()</code></p></li><li class="li"><p>Calling <code>NS_VOIDRETURN</code></p></li><li class="li"><p>“Falling off the end”</p></li></ul><p>The above example raises an exception when <code>someError</code> is <code>YES</code>. Alternatively, you can return control to the caller from within the exception handling domain by calling either <code>NS_VALUERETURN()</code> or <code>NS_VOIDRETURN</code>. “Falling off the end” is simply the normal path of execution—after all statements in the exception handling domain are executed, execution continues on the line following <code>NS_ENDHANDLER</code>.</p><div class="notebox"><a name="//apple_ref/doc/uid/20000059-DontLinkElementID_20" title="Note"></a><p><strong>Note:</strong>&nbsp;You cannot use <code>goto</code> or <code>return</code> to exit an exception handling domain—errors will result. Nor can you use the <code>setjmp</code> and <code>longjmp</code> functions if the jump entails crossing an <code>NS_DURING</code> statement. Since the code that your program calls may have exception-handling domains within it, avoid using <code>setjmp</code> and <code>longjmp</code> in your application.</p></div><p>Similarly, you can leave the local exception handler (the section of code between <code>NS_HANDLER</code> and <code>NS_ENDHANDLER</code>) by raising an exception or simply “falling off the end”.</p>

        <br/><br/> 

        <div class="mini_nav_text" align="left">
        <span class="navButtons">
        <a href="../Concepts/PredefinedExceptions.html">&lt; Previous Page</a><span style="margin-left: 8px"><a href="RaisingExceptions.html">Next Page &gt;</a></span>
        </span>
        <span id="showHideTOCLowerSpan">
        <a href="#" onclick="showHideTOC();"><img src="../../../../Resources/Images/show_toc_icon.gif" width="15" height="14" border="0" style="margin-bottom: -2px;" alt="" /></a> <a href="#" onclick="showHideTOC();">Hide TOC</a>
        </span>
        </div>

        <br/><hr /><div align="center"><p class="content_text" lang="en" dir="ltr"> <!--#if expr="0=1" -->&#x00a9; 2002, 2007 Apple Inc. All Rights Reserved. &#40;<!--#endif -->Last updated: 2007-10-02<!--#if expr="0=1" -->&#041;<!--#endif --></p></div>

        
        <div class="hideOnPrint hideInXcode">
        <!-- start of footer -->
        	<table width="100%" border="0" cellpadding="0" cellspacing="0">
		<tr>
			<td><div style="width: 100%; height: 1px; background-color: #919699; margin-top: 5px; margin-bottom: 15px"></div></td>
		</tr>
		<tr>
			<td align="center"><br/>
				<table border="0" cellpadding="0" cellspacing="0" class="graybox">
					<tr>
						<th>Did this document help you?</th>
					</tr>
					<tr>
						<td>
						    <div style="margin-bottom: 8px"><a href="http://developer.apple.com/feedback/?v=1&url=/documentation/Cocoa/Conceptual/Exceptions/Tasks/HandlingExceptions.html%3Fid%3D10000012i-3.2&media=dvd" target=_new>Yes</a>:  Tell us what works for you.</div>
							<div style="margin-bottom: 8px"><a href="http://developer.apple.com/feedback/?v=2&url=/documentation/Cocoa/Conceptual/Exceptions/Tasks/HandlingExceptions.html%3Fid%3D10000012i-3.2&media=dvd" target=_new>It&#8217;s good, but:</a> Report typos, inaccuracies, and so forth.</div>
							<div><a href="http://developer.apple.com/feedback/?v=3&url=/documentation/Cocoa/Conceptual/Exceptions/Tasks/HandlingExceptions.html%3Fid%3D10000012i-3.2&media=dvd" target=_new>It wasn&#8217;t helpful</a>: Tell us what would have helped.</div>
						</td>
					</tr>
				</table>
			</td>
		</tr>
	</table>

        <!--#include virtual="/includes/framesetfooter" -->
        <!-- end of footer -->
        </div>
    </div>
</body>
</html>
